# Generated by Django 3.2.4 on 2021-07-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockCsvFiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('csv_file', models.FileField(upload_to='')),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
    ]
